# .readthedocs.yml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    - apt-get update
    - apt-get install -y some-package

python:
  install:
    - requirements: requirements.txt
