version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    apt_update:
      commands:
        - sudo apt-get update
    install_dependencies:
      commands:
        - sudo apt-get install -y some-package

python:
  install:
    - requirements: requirements.txt
