version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - libgl1-mesa-glx
    - libosmesa6
    - freeglut3-dev

sphinx:
  # Adjust this if your conf.py is also in the root
  configuration: docs/conf.py 

formats:
  - pdf

python:
  install:
    # Pointing to the requirements.txt in your main (root) folder
    - requirements: requirements.txt
