version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - libgl1-mesa-glx
    - libosmesa6
    - freeglut3-dev

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

python:
  install:
    - requirements: requirements.txt
