version: 2

# Define the operating system and Python version
os: ubuntu-22.04
python:
  version: "3.11"
  install:
    - requirements: requirements.txt

# Lifecycle hooks for system-level commands
post_system_dependencies:
  - sudo apt-get update
  - sudo apt-get install -y some-package

# Sphinx configuration (required)
sphinx:
  configuration: docs/conf.py
