version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  post_system_dependencies:
    commands:
      - sudo apt-get update
      - sudo apt-get install -y some-package

python:
  install:
    - requirements: requirements.txt
